---
title: "wetenschappelijke cyclus"
author: "alexander"
date: "2026-05-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


om de databestanden in te lezen hebben we readr nodig, die hier wordt ingeladen.
als je deze nog niet hebt moet je de lijn install.packages("readr") runnen.
```{r}
install.packages("readr")
library(readr)
```



```{r}

file <- read.csv("../../raw_data/heartrate_1.csv")
file
subset_file <- file[2:3]
subset_file
subset_file <- subset_file[3:length(subset_file$Sport),]
colnames(subset_file)<- c("Time", "HR (bpm)")
subset_file


```



```{r}
read_and_filter <- function(filelocation, testtime_1, testtime_2, testtime_3) {
  
  #eerst maakt deze functie een subset van het bestand
  file <- read.csv(filelocation)
  subset_file <- file[, 2:3]
  subset_file <- subset_file[3:nrow(subset_file), ]
  colnames(subset_file) <- c("time", "HR_bpm")

  #uit die subset haalt de functie de hartslagen over de gespecificeerde tijd en maakt deze numeriek
  results_1 <- as.numeric(subset_file$HR_bpm[testtime_1])
  results_2 <- as.numeric(subset_file$HR_bpm[testtime_2])
  results_3 <- as.numeric(subset_file$HR_bpm[testtime_3])

  # return alles als een list
  return(list(
    results_1 = results_1,
    results_2 = results_2,
    results_3 = results_3
  ))
}

testtime_1 <- 298:389
testtime_2 <- 455:516
testtime_3 <- 590:621
data_list <- read_and_filter("../../raw_data/heartrate_1.csv",testtime_1,testtime_2, testtime_3)
data_list
```


```{r}
test_tijden <- read.csv("../../raw_data/testtijden.csv")
files <- list.files("../../raw_data/", pattern = "heartrate", full.names = TRUE)
files
#list.files("../../raw_data/")

#files

all_results <- lapply(seq_along(files), function(x) {
  
  heartrate_locatie <- files[x]
  
  testtime_1 <- test_tijden$Geen.tijdsdruk.start[x] : test_tijden$geen.tijdsdruk.eind[x]
  
  testtime_2 <- test_tijden$Licht.tijdsdruk.start[x] : test_tijden$lichte.tijdsdruk.eind[x]

  testtime_3 <- test_tijden$Hoge.tijdsdruk.start[x] : test_tijden$hoge.tijdsdruk.eind[x]

  read_and_filter(heartrate_locatie, testtime_1, testtime_2, testtime_3)
})


all_results


results1 <- all_results[[1]]$results_3
results1
x <- 1:length(results1)
coef(lm(results1~x))[2]
plot(results1)

```


