---
title: "logboek"
author: "alexander"
date: "2026-05-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## introductie 
Studenten ervaren over het algemeen erg veel stress door school, zoals gebleken uit het rapport van Monitor Mentale Gezondheid en Middelengebruik Studenten hoger onderwijs (MMMS). Met ons onderzoek proberen wij de stress te meten, door de hartslag en bloeddruk te meten tijdens en na het maken van korte rekentoetsen. Deze rekentoetsen worden onder variërende tijdsdruk gemaakt.

al onze data en gegevens zijn te vinden op https://github.com/alexanderathanze/wetenschappelijke-cyclus.git

De onderzoeksvraag luidt als volgt: Heeft tijdsdruk effect op de prestatie, bloeddruk en hartslag van studenten.

onze H0 is dat studenten onder tijdsdruk niet significant meer stress ervaren. 
onze H1 is dat studenten onder tijdsdruk wel significant meer stress ervaren. 


Daarnaast hebben wij twee nevenvragen: 

Heeft de dagelijks ervaren stress invloed op de stress onder tijdsdruk?

H0: De dagelijks ervaren stress heeft invloed op de stress onder tijdsdruk.
H1: De dagelijks ervaren stress heeft geen invloed op de stress onder tijdsdruk.

Heeft sexe invloed op ervaren stress onder tijdsdruk?

H0: De sexe heeft geen invloed op de ervaren stress onder tijdsdruk.
H1: De sexe heeft invloed op de ervaren stress onder tijdsdruk. 


## Data
WIP




## 20/5/2026

### doel van de dag
Vandaag is het doel om zo veel mogelijk mensen te meten. Dit wordt gedaan zoals
in het protocol vermeld.

### motivatie van aanpak
Dit doel is gekozen omdat er nog veel data verzameld moet worden. Door het 
verzamelen van deze data kunnen wij zo snel mogelijk verder met ons onderzoek. 

### uitgevoerde werkzaamheden
Er zijn een aantal proefpersonen getest en gemeten zoals vermeld in het protocol.

### resultaten
Er zijn succesvol gegevens verzameld van een aantal mensen. 

### conclusie en vervolgstappen
De volgende dag moeten er nog meer mensen getest en gemeten worden.





## 21/5/2026

### doel van de dag
Vandaag is het doel om het artikel tot zover het er is (introductie,
materiaal en methoden) aan te passen zodat deze klopt en actueel is. 

### motivatie van aanpak
dit doel is gekozen omdat we het artikel nog actueel moeten maken. Dit zorgt er voor dat we een beter reproduceerbaar expirment hebben.

### uitgevoerde werkzaamheden
het protocol en de introductie zijn aangescherpt, de oude informatie is voor het grootste deel vervangen. Voor de introductie is er meer uitleg over de pss verzameld. Ook is er nog een persoon getest.

### resultaten
het protocol en de introductie zijn aangescherpt en er is succesvol een persoon getest.

### conclusie en vervolgstappen
een volgende dag/sessie moeten er nog personen getest worden voor ons onderzoek.



# 22/5/2026

### doel van de dag
eerder gemaakte werk in een repo zetten 

### motivatie van aanpak
repos zijn handiger om in terug te vinden wat er is gebeurd. Ook moet het uiteindelijk gemaakte werk in een repo ingeleverd worden. 

### uitgevoerde werkzaamheden
de meeste dingen zijn in een repo omgezet, m.u.v. rauwe data en 2 logboeken door afwezigheid van groepsgenoten

### resultaten
alle tot nu toe gemaakte bestanden zitten in de repo, m.u.v. bestanden vermeld in uitgevoerde werkzaamheden

### conclusie en vervolgstappen
alle rauwe data en logboeken moeten nog in de repo gezet worden.



##26/5/2026

### doel van de dag
de tot nu toe verzamelde data van 11 personen online opvragen en deze data filteren op tijd en hartslag. Hiervan moet in de tabel met toetsscores (wetenschappelijke_cyclus/raw_data/wetcyc.xlsx) een nieuwe rij toegevoegd worden waarin de hartslagen per situatie (geen, lage en hoge tijdsdruk) in staan.

### motivatie van aanpak
de data moet in één document in tabelvorm komen zodat deze voor verdere verwerking en statistiek goed te gebruiken is. 

### uitgevoerde werkzaamheden
er is een begin gemaakt aan het script om data mee te verwerken. De geschreven code is in de repo terug te vinden in commit hash 0967af086218ce1985df5bfbd43198639c626fd7. ik was er even tegenaan gelopen hoe ik subsets moest maken van de rauwe data, maar dat is ook opgelost. verder is er nog een testpersoon gemeten in lokaal D1.08 Door Tristan, Jasmijn en ik.

### resultaten
De geschreven code filtert tot nu toe uit een van de rauwe databestanden (wetenschappelijke_cyclus/raw_data/heartrate_1.csv) de tijd en hartslagen in bpm.

### conclusie en vervolgstappen
er moet nog veel gedaan worden. Ten eerste is onze data nog niet compleet, aangezien we afgesproken hebben om van minimaal 20 personen de data te verzamelen. daarnaast moet de poweranalyse nog gedaan worden en is de code om alle data te verwerken ook nog niet af. na deze stappen kan er pas verder gewerkt worden aan de resultaten, maar een deel van de discussie zou evt wel al gemaakt kunnen worden.



##27/5/2026

### doel van de dag
de eerder geschreven code moet in een functie gezet worden, zodat deze op alle andere documenten met de hartslag (/raw_data/heartrate_x.csv, waarin x een geheel getal). 

### motivatie van aanpak
de data moet in één document in tabelvorm komen zodat deze voor verdere verwerking en statistiek goed te gebruiken is. door weinig tijd is de stap vandaag relatief klein. 

### uitgevoerde werkzaamheden
er is van de eerder geschreven code (zie 26/5/2026 of git hash 0967af086218ce1985df5bfbd43198639c626fd7) een functie gemaakt.  verder is er nog een testpersoon gemeten door Jasmijn en ik, waardoor we nu op 13/20 personen zitten.


### resultaten
de functie is geschreven en werkzaam. de code hiervoor is terug te vinden in wetenschappelijke_cyclus/analysis/scripts/wetenschappelijke_cyclus.Rmd in git hash 2cbe08dcec567d95a80cb3c228724519cd8433a5.

### conclusie en vervolgstappen
er moeten nog 7 personen gemeten worden voor onze data, waarvan het liefst nog 1 man en 6 vrouwen. in scripts moet er nog veel geschreven worden, om onze data nog verder te filteren op tijd tijdens de test. daarnaast moet de dan gefilterde data nog in een nieuwe tabel gezet worden. ook moet de poweranalyse, resultaten en discussie nog geschreven/gedaan worden in onze paper. 



##29/5/2026

### doel van de dag
mensen testen en het eerder gemaakte script proberen te laten filteren op de testtijden

### motivatie van aanpak
dit is de volgende stap in het dataverwerkingprocess. door de testtijden uit de eerder gegenereerde gegevens te krijgen kunnen wij verder met de analyse. daarnaast is onze data nog niet compleet, dus moeten wij nog mensen testen

### uitgevoerde werkzaamheden
er is 1 persoon getest in lokaal D1.07. de test is uitgevoert door Tristan, Jasmijn en ik. voor de test liep de bloeddrukmeter leeg, waarna daar batterijen voor zijn gehaald. de testpersoon was meegelopen en heeft als correctie op de inspanning 2 extra minuten rust gekregen. verder is er gewerkt aan de code, zodat deze op testtijden kan filteren. 


### resultaten
doordat er een test is uitgevoerd, zitten we op 14/20 personen, waarvan de rest met voorkeur vrouwelijk is. verder is de code zo aangepast dat deze nu ook op testtijden kan filteren, voor meer detais zie git hash 1141ef2a9cbcddf9309e2158799d3a170df47373.

### conclusie en vervolgstappen
er moeten nog 6 personen gemeten worden, bij voorkeur allemaal vrouw. ons script moet nog verder geschreven worden, zodat deze uiteindelijk de data in de tabel met andere gegevens (raw_data/wetcyc.xlsx) kan zetten. 


## 30/5/2026
### doel van de dag
de code voor de analyse verder/af proberen te krijgen

### motivatie van aanpak
doordat we in het weekend geen mensen kunnen testen en de deadline nadert, moeten we er voor zorgen dat de analyse van data zo snel mogelijk kan nadat de data er is. om dit te kunnen doen moet het script voor de data analyse afgemaakt worden, wat de reden is voor dit doel. 

### uitgevoerde werkzaamheden
er is een stuk code toegevoegd die automatisch de hartslagen tijdens het maken van de tests filtert uit de volle meting, door middel van de genoteerde start/eindtijd. daarnaast is er een stuk toegevoegd waarmee de code de "slopes" van de trendlijn uit de data kan halen. dit is een gegeven die nodig is voor de daadwerkelijke analyse van de data. de volledige details van de toegevoegde code zijn te vinden in git hash 53eb6c59caa86d78cb510288c8c4b8e4ee606d48. 
tijdens het schrijven van deze code ben ik tegen wat dingen aangelopen. eerst had ik de code zo geschreven dat deze gehardcode de namen van de data bij langs ging in de juiste map. na het inzien dat dit niet helemaal goed is, heb ik dit veranderd (met moeite) naar een manier van inlezen waarbij hij de juiste map 'scant' voor bestanden met "heartrate" in de naam. deze code werkt nu.


### resultaten
de code voor de analyse kan nu de juiste datapunten uit de vele csv-bestanden halen en kan voor een deel van deze datapunten de slope berekenen. 

### conclusie en vervolgstappen
er moet nog verder gewerkt worden aan het programma voor data-analyse en de metingen moeten afgemaakt worden.  
