---
title: "Logboek"
author: "Tristan Kruithof"
date: '`r Sys.Date()`'
output: html_document
---


## Notities

Wat kan er beter aan dit logboek?

- project beschrijving (locatie bestanden)
- installatie apps bloedddruk en hartslag


# Levensverwachting en leefstijl 

### Introductie

Ik ga onderzoek doen naar geïnterpreteerde stress doormiddel van bloeddruk en hartslag tijdens het maken van een rekentoets onder verschillende tijd drukken.


### Motivatie:

Omdat stress bij het maken van toetsen een negatieve impact heeft op je prestatie, wordt in dit onderzoek beter in kaart gebracht hoe stress wordt ervaren tijdens het maken van toetsen onder tijdsdruk. 


### Hoofdvraag:

Beïnvloedt een tijdsdruk de bloeddruk, hartslag en de prestatie?


### hoofddoel:

Onderzoeken in hoeverre tijdsdruk invloed heeft op de:

Bloeddruk voor/na het maken van rekensommen
Hartslag voor/tijdens/na het maken van rekensommen
Prestatie op rekentaken (aantal goede antwoorden, fouten, snelheid)


### Onze nevenvragen:

- Heeft dagelijks ervaren stress (door middel van een HADS of PSS vragenlijst) invloed op het gemeten verschil in bloeddruk, hartslag en  prestatie?

- Is er een verschil in bloeddruk, hartslag en prestatie tussen de sexes?


### Data die wij verkrijgen per test persoon: 

- Toestemming annoniem opslaan van gegevens
- Leeftijd
- Geslacht
- PSS-10 vragen lijst (indicatie van stress in het dagelijks leven)
- Gemeten bloeddruk voor/na elke toets in mmHg, verdeeld in bovendruk en onderdruk
- Gemeten hartslag tijdens de gehele test in BPM
- Testscores van de 3 rekentests 

Deze data wordt naderhand gelijk verwerkt zodat de totale score van de testen en de PSS-10 vragenlijst wordt bewaard. De bloeddruk en hartslag wordt opgeslagen op een account van Polar ()  en Omron (bloeddruk meter)

De inviduele antwoorden zijn door ons niet meer te zien nadat wij deze data verwijderd hebben.


### Github Repo (zie voor meer info over ons onderzoek)

https://github.com/alexanderathanze/wetenschappelijke-cyclus/tree/main  

Route van rauwe data:
raw_data/ (heart beats, blood pressure, test scores)

Route van R scripts: 
analysis/ (boxplots, line plots for blood pressure, heart beats and test scores)


# Logboek

## 19/05/2026
Doel: Artikel vinden voor journal club, meet methode uittesten op onszelf en eventueel verbeteren.

Motivatie: Onze meet methode is nog niet robuust en hebben we nog niet echt uitgetest, daarom moeten we dat doen. En ik loop al achter met een artikel kiezen voor de journal club, daarom moet ik daar vandaag naar opzoek.


Artikel gevonden voor de journal club en daarbij in teams gezet dat ik het graag op 29 mei om half 11 presenteer. Dit artikel heb ik een tijdje geleden al gevonden toen ik er een youtube video over keek.

Artikel titel: H-Neurons: On the Existence, Impact, and Origin of Hallucination-Associated Neurons in LLMs en

link:https://arxiv.org/abs/2512.01797

Samenvatting artikel: Het artikel gaat over waar precies hallucinaties gebeuren in een LLM model (large language model). De onderzoekers hebben ontdekt welke neuronen in een netwerk precies zorgen voor hallucinaties en welke juist horen bij 


Ook hebben we getest op onszelf en gediscussieerd over onze meetmethode en hebben we deze verbeterd doormiddel van noteren van starttijd toetsen en hebben ons protocol over begeleiden van het proefpersoon tijdens de test ook verbeterd.


## 20/05/2026
We zijn verder gegaan met onze metingen. Om 10:36 en hebben klasgenoten elk voor elk eruit gehaald om te testen. Elk van deze metingen slaan we op doormiddel van het exporteren van een google forms. Ondertussen noteren wij de starttijd van elk toetsje erbij ook in excel. En halen we de data op van de bloeddruk- en hartslagmeter door deze apparaten geconnect te hebben met beide apps van Polar en .

Ondertussen heb ik gewerkt aan mijn logboek en heb ik een stukje informatie opgezocht over wat bloeddruk inhoudt en dit verwerkt in de intro van ons artikel met bronvermelding. Bron: https://www.hartstichting.nl/oorzaken/bloeddruk


Ook heb ik een stukje geschreven over de hartslag met de volgende bronnen: https://www.hartstichting.nl/gezond-leven/hartslag/normale-hartslag [9] - hartslag
https://www.hartstichting.nl/hart-en-vaatziekten/bouw-en-werking-hart [10] - hart werking
https://www.ahealthylife.nl/medisch-woordenboek/hf/ [11] - hartslag afkorting


## 21/05/2026
We waren in de ochtend begonnen met beter leren schrijven. Een abstract beter leren schrijven. Het onderwerp, uitkomsten en conclusie moest je zelf allemaal verzinnen, vervolgens werden tussen 3 artikel, 1 gemaakt door ai, 1 echt artikel online en je eigen verzonnen artikel. De persoon met de meeste punten kreeg een chocolade letter. 

Daarna heb ik gewerkt aan een stukje schrijven over de pss-10 test met al bestaande bronnen in het document en heb ik referenties aangepast. Dit kun je terug vinden in de repo. Ook heb ik een korte hypothese geschreven op basis een vergelijkbaar artikel (https://minds.wisconsin.edu/handle/1793/80216) dat wij aan het schrijven zijn, waar uit kwam dat er niet een significant verschil is in bloeddruk en hartslag. Wel had dat artikel een andere methode van meten gebruikt dan wij dat hebben gedaan. 


## 22 t/m 25 mei
22 mei was ik ziek en daarna was het pinkster weekend.


## 26/05/2026

Doel: Aan het einde van de dag nog een meting doen van een meid. Begin maken aan de R code voor ons onderzoek. Logboek verbeteren op basis van feedback en van journal club artikel een presentatie maken.

Motivatie: Moeten nog genoeg metingen doen om te komen bij de 20 metingen. En moeten nog code schrijven voor onze statistische analyse.

Bezig gegaan met deel 2 van de FAIR. Een repository was aangemaakt op github door Alexander op 22 mei:
https://github.com/alexanderathanze/wetenschappelijke-cyclus/tree/main

Hebben gekeken naar eventuele oplossingen voor hoe wij onze data gaan verwerken en wat we nodig hebben voor een juiste conclusie van ons onderzoek. En hebben een meting gedaan.

Conclusie: Ik heb minder gedaan dan ik wilde doen. Maar we hebben een meting gedaan aan het einde van de dag. En ook gekeken naar eventuele manieren van visualiseren, alleen hier waren we nog niet compleet uit gekomen, want wij wisten niet precies wat wij statistisch uit onze data konden halen en hoe/wat de beste manier daarvan is. 

## 27 t/m 28 mei

Doel: Bezig met ons onderzoek, maar vooral bezig met de journal club, want ik heb op 29 mei een presentatie daarvan.

Motivatie: Ik heb vrijdag 29 mei een presentatie over hallucinaties in LLM's en deze presentatie moest al worden ingeleverd op 27 mei op 9.00 's ochtends. Artikel: https://arxiv.org/abs/2512.01797

Ik was erg ziek en moest de presentatie maken. Ik heb het artikel goed doorgelezen, ook was er een in-depth youtube video over gemaakt: https://www.youtube.com/watch?v=1ONwQzauqkc. Vervolgens heb ik voor plaatjes en feitjes ook nog andere bronnen opgezocht: 

Gao, C. e.a. (2025). H-Neurons: On the Existence, Impact, and Origin of Hallucination-Associated Neurons in LLMs. arXiv:2512.01797.
Stanford HAI (2026). 2026 AI Index Report – Responsible AI. hai.stanford.edu/ai-index/2026-ai-index-report/responsible-ai
Artificialanalysis.ai (2026) - AA-Omniscience: Knowledge and Hallucination Benchmark https://artificialanalysis.ai/evaluations/omniscience
Bao et al. (2025). DeepSeek-R1 Hallucinates More Than DeepSeek-V3.
Kalai, A. et al. (2025). Why Language Models Hallucinate. arXiv:2501.06521.
Chelli, M. et al. (2024). Hallucination Rates and Reference Accuracy of ChatGPT and Bard. JMIR. doi:10.2196/53164


conclusie: Decent presentatie gemaakt over het artikel, niet echt bezig geweest met het onderzoek helaas.

## 29/05/2026

Doel: 
Presentatie geven en nog een meting doen.

Motivatie: 
Presentatie moeten geven en we hebben nog niet genoeg metingen gedaan. Want we moeten nog 20 metingen doen en hebben er maar 14. 

Conclusie:
Wij hebben de gehele dag op school presentaties gedaan en na de les hebben we nog een meting gedaan van een man en de batterijen vervangen van het bloeddruk meter apparaat. Presentatie ging prima, was aantal dingen ondertussen vergeten waardoor ik er later nog op terug moest komen. 


## 31/05/2026

Doel:
R code schrijven voor de data uit de bloeddruk meter.

Motivatie: Wij hebben nog lang niet alle R code geschreven, dus wij moeten dat zo snel mogelijk doen. 

Bezig gegaan met R script voor de bloeddruk data.

Repo: zie bovenaan document

Script: Analysis/bloodpressure.rmd

data: raw data/Blood pressure/bloodpressure.xslx

Conclusie: Een klein begin kunnen maken, alleen in de trein was het zo druk dat ik moest staan en niet echt bezig kon gaan.

## 1/05

Doel:
Verder gaan met R code schrijven voor de data van de bloeddruk meter en bespreken wat voor plotjes we moeten maken voor de rest.
Eventueel verder meten.

Motivatie: 
Ik heb de code ervoor nog lang niet af en had maar een begin gemaakt, het moet af dus ik moet ermee bezig. Ook moeten we samen bespreken welke plotjes van waarde zijn voor ons onderzoek. Nog steeds geen 



Conclusie:




 
